[package]
name = "rust-wgpu-gui-example"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "23.0.0"
futures = "0.3"
pollster = "0.3"
bytemuck = { version = "1.19.0", features = ["derive"] }
glyphon = "0.7.0"
winit = "0.30.5"
