[package]
name = "rust-wgpu-gui-example"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
pollster = "0.3"
bytemuck = { version = "1.19.0", features = ["derive"] }
glyphon = "0.7.0"
winit = "0.30.5"
egui = "0.29.1"
egui-wgpu = "0.29.1"
egui-winit = "0.29.1"

[profile.dev]
opt-level=0

[profile.release]
opt-level=0
